### ISSUE TITLE
There is a chance that vmess will fail

### ISSUE THREAD

**Issue by photkey** [arminmokri/v2ray2json#3]
This node added to v2rayN is added normally, but then an exception is thrown, as follows:
`vmess://ewogICAgImFkZCI6ICIxajhwMDUuYWJ6b29uZXMueHl6IiwKICAgICJhaWQiOiAwLAogICAgImhvc3QiOiAiIiwKICAgICJpZCI6ICJhZGYzOTljNS1mNzE1LTRlMTYtYjgzNy01OGY0NDEwZTJhOWIiLAogICAgIm5ldCI6ICJ0Y3AiLAogICAgInBhdGgiOiAiIiwKICAgICJwb3J0IjogMzYxMDYsCiAgICAicHMiOiAi8J+HqPCfh7NfQ05f5Lit5Zu9LVx1MDAzZfCfh6/wn4e1X0pQX+aXpeacrCIsCiAgICAidGxzIjogInRscyIsCiAgICAidHlwZSI6ICJub25lIiwKICAgICJzZWN1cml0eSI6ICJub25lIiwKICAgICJza2lwLWNlcnQtdmVyaWZ5IjogdHJ1ZSwKICAgICJzbmkiOiAiIgp9`
```Traceback (most recent call last):
  File "D:\DevScript\V2rayCheck\v2ray\format.py", line 45, in <module>
    print(generateConfig(node_))
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\DevScript\V2rayCheck\v2ray\v2ray2json.py", line 1146, in generateConfig
    vmessQRCode = VmessQRCode(**_json)
                  ^^^^^^^^^^^^^^^^^^^^
TypeError: VmessQRCode.__init__() got an unexpected keyword argument 'security'```

**Comment by arminmokri** [comment]
hello
I checked your vmess link it is not version 2, it has 2 extra parameters "security" and "skip-cert-verify" but i change my project to skip it.
